#!/usr/bin/env bash                                               
# Configure new server --> engine-x                               
                                                                  
sudo apt-get -y update                                            
sudo apt-get -y install nginx                                     
sudo ufw allow 'Nginx HTTP'                                       
                                                                  
sudo sed -i 's/http {/&\n\tadd_header X-Served-By $HOSTNAME;/' /etc/nginx/nginx.conf
sudo service nginx restart
